### PR TITLE
Jobrunner configurable channels

### PR DESCRIPTION
**Pull request by guewen**
Allow to configure the channels on the job functions

With 2 new models: queue.job.channel and queue.job.function
The channels are a tree starting from 'root' which is a mandatory channel and
each job function (decorated with @job) can be assigned to a channel.

The channels names should correspond to the one used when the runner is launched.

I had to rebase on origin/8.0, that's why there are so many commits, but one the base branch is rebased I will rebase my branch on it again. (only the 3 last are of interest)

### CODE REVIEW

**Comment by guewen** [comment]
@sbidoul should it be possible to have several root channels?

**Comment by sbidoul** [comment]
@guewen What's your use case for multiple root channels? 

In my view, configuration of the root channel is server administrator's responsibility to define how many concurrent jobs can run and is defined in the startup script in relation with the --workers Odoo option.

**Comment by sbidoul** [comment]
@guewen I cherry-picked your last three commit in https://github.com/OCA/connector/issues/52.

I had a hard time undertanding why my job functions did not appear, until I realized I had to create an abstract model to signal that base_import_async was installed.

Seems to work fine at first glance.

**Comment by guewen** [comment]
> @guewen What's your use case for multiple root channels?
> 
> In my view, configuration of the root channel is server administrator's responsibility to define how many concurrent jobs can run and is defined in the startup script in relation with the --workers Odoo option.

No use case. I had the same view than your's when writing this code, then suddenly wondered if I was missing some use cases. All is fine.

**Comment by guewen** [comment]
> @guewen I cherry-picked your last three commit in OCA#52.

Thanks!

> I had a hard time undertanding why my job functions did not appear, until I realized I had to create an abstract model to signal that base_import_async was installed.

Did you reported it on `base_import_async`?
It is a bug in this module, all modules that inherits from `connector` must register themselves: http://odoo-connector.com/guides/bootstrap_connector.html#install-the-module-in-the-connector (`install_in_connector()` creates the abstract model)

> Seems to work fine at first glance.

Excellent

**Comment by guewen** [comment]
I guess I can close this PR

**Comment by sbidoul** [comment]
@guewen thanks for the pointer to the documentation. 
The fix is in https://github.com/OCA/connector-interfaces/pull/13

**Pull request closed without merging**
